import type { Metadata, Viewport } from "next";
import "./globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "iDekTep-Tracking-System",
  description: "Generated by create next app",
  generator: "Next.js",
  keywords: ["idektep","Idektep tracking","Idektep", "IDektep", "ไอเดกเทพ", ],
  authors: [
    { name: "IDektep-Developer-Team" },
    {
      name: "IDektep-Information",
      url: "https://idektep.com/",
    },
  ],
  icons: [
    { rel: "apple-touch-icon", url: "/images/logo/idektep-192.png" },
    { rel: "icon", url: "/images/logo/idektep-192.png" },
  ],
};


export const viewport: Viewport = {
  themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#73408A" }],
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#E3E3E3]">
        <Image
          className=" PC absolute top-0 -z-10 w-full h-4/6 blur-[25px] hidden md:block"
          src={"/images/signIn/bg-cover-1.png"}
          width={0}
          height={0}
          alt="children"
        />
        <Image 
          className=" mobile absolute w-full h-4/6 blur-[25px] block md:hidden -z-10"
          src={"/images/form/bg-cover.png"}
          width={0}
          height={0}
          alt="background"
        />
        {children}
      </body>
    </html>
  );
}